version: '3.8'

services:
  mysql:
    image: ${HARBOR_REGISTRY}/mysql-repo/mysql-custom:latest
    container_name: mysql-server
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=yin
      - MYSQL_PASSWORD=123456
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
    driver: local

networks:
  mysql-network:
    driver: bridge
